import os
import csv
import time
import uuid
import shutil
import asyncio
import logging
from pathlib import Path
from fastapi import UploadFile

from app.core.config import settings
from app.core.exceptions import InvalidAudioError, BirdNetExecutionError, CsvParsingError
from app.schemas.bird import BirdDetection, BirdAnalysisResponse

logger = logging.getLogger("birdsense.services.birdnet")

ALLOWED_EXTENSIONS = {".wav", ".mp3", ".flac", ".ogg", ".m4a"}

class BirdNetService:
    def __init__(self):
        self.upload_dir = Path(settings.UPLOAD_DIR)
        self.output_dir = Path(settings.OUTPUT_DIR)
        
        self.upload_dir.mkdir(parents=True, exist_ok=True)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def validate_file(self, filename: str, file_size: int | None) -> None:
        if not filename:
            raise InvalidAudioError("No filename provided")
        
        if file_size is not None:
            size_mb = file_size / (1024 * 1024)
            if size_mb > settings.MAX_UPLOAD_SIZE_MB:
                raise InvalidAudioError(f"File too large. Maximum size is {settings.MAX_UPLOAD_SIZE_MB}MB.")
                
        ext = Path(filename).suffix.lower()
        if ext not in ALLOWED_EXTENSIONS:
            raise InvalidAudioError(f"Unsupported audio format. Allowed: {', '.join(ALLOWED_EXTENSIONS)}")

    async def save_upload_file(self, upload_file: UploadFile, dest_path: Path) -> None:
        try:
            with dest_path.open("wb") as buffer:
                shutil.copyfileobj(upload_file.file, buffer)
        except Exception as e:
            logger.error(f"Failed to save upload file: {str(e)}")
            raise InvalidAudioError("Could not save the uploaded file")

    async def run_birdnet(self, input_path: Path, output_dir: Path) -> None:
        import sys
        import shutil
        
        birdnet_cmd = settings.BIRDNET_COMMAND
        if not shutil.which(birdnet_cmd):
            python_dir = Path(sys.executable).parent
            if (python_dir / "birdnet-analyze.exe").exists():
                birdnet_cmd = str(python_dir / "birdnet-analyze.exe")
            elif (python_dir / "birdnet-analyze").exists():
                birdnet_cmd = str(python_dir / "birdnet-analyze")
            else:
                venv_path = Path("venv/Scripts/birdnet-analyze.exe").absolute()
                if venv_path.exists():
                    birdnet_cmd = str(venv_path)
                    
        logger.info(f"Resolved BirdNET executable to: {birdnet_cmd}")
                
        cmd = [
            birdnet_cmd,
            "--lat", str(settings.DEFAULT_LATITUDE),
            "--lon", str(settings.DEFAULT_LONGITUDE),
            "--min_conf", str(settings.MIN_CONFIDENCE),
            "--rtype", "csv",
            "--output", str(output_dir),
            str(input_path)
        ]
        
        logger.info(f"Starting BirdNET analysis: {' '.join(cmd)}")
        
        try:
            def run_cmd():
                import subprocess
                return subprocess.run(
                    cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    check=False
                )
            
            process = await asyncio.to_thread(run_cmd)
            
            if process.returncode != 0:
                err_msg = process.stderr.decode('utf-8', errors='replace').strip()
                logger.error(f"BirdNET execution failed with code {process.returncode}: {err_msg}")
                raise BirdNetExecutionError(f"BirdNET analysis failed: {err_msg}")
                
            logger.info("BirdNET analysis completed successfully")
        except FileNotFoundError:
            logger.error(f"BirdNET command '{settings.BIRDNET_COMMAND}' not found.")
            raise BirdNetExecutionError("BirdNET is not installed or not in PATH")
        except Exception as e:
            if not isinstance(e, BirdNetExecutionError):
                logger.error(f"Unexpected error running BirdNET: {repr(e)}")
                raise BirdNetExecutionError(f"Unexpected error during analysis: {repr(e)}")
            raise

    def parse_results(self, output_path: Path) -> list[BirdDetection]:
        detections = []
        if not output_path.exists():
            # Sometimes BirdNET fails silently or creates a slightly different filename.
            # We'll just return empty if not found, or raise an error.
            # Raising is safer for debugging.
            raise CsvParsingError("Output CSV not generated by BirdNET")
            
        try:
            with open(output_path, mode='r', encoding='utf-8') as csvfile:
                # Read the first line to determine delimiter
                first_line = csvfile.readline()
                csvfile.seek(0)
                delimiter = ';' if ';' in first_line else ','
                if '\t' in first_line:
                    delimiter = '\t'
                    
                reader = csv.DictReader(csvfile, delimiter=delimiter)
                for row in reader:
                    # Map the standard BirdNET column names
                    start = float(row['Start (s)'])
                    end = float(row['End (s)'])
                    scientific_name = row['Scientific name']
                    common_name = row['Common name']
                    confidence = float(row['Confidence'])
                    
                    detections.append(BirdDetection(
                        common_name=common_name,
                        scientific_name=scientific_name,
                        confidence=confidence,
                        start_time=start,
                        end_time=end
                    ))
            logger.info(f"Parsed {len(detections)} detections from {output_path.name}")
        except Exception as e:
            logger.error(f"Failed to parse CSV {output_path}: {str(e)}")
            raise CsvParsingError(f"Error parsing results: {str(e)}")
            
        return detections

    async def analyze(self, file: UploadFile) -> BirdAnalysisResponse:
        logger.info(f"Upload started: {file.filename}")
        self.validate_file(file.filename, file.size)
        
        file_id = str(uuid.uuid4())
        ext = Path(file.filename).suffix
        
        temp_audio_path = self.upload_dir / f"{file_id}{ext}"
        temp_output_dir = self.output_dir / file_id
        temp_output_dir.mkdir(parents=True, exist_ok=True)
        
        await self.save_upload_file(file, temp_audio_path)
        logger.info(f"Upload completed: {temp_audio_path.name}")
        
        start_time = time.time()
        
        try:
            await self.run_birdnet(temp_audio_path, temp_output_dir)
            
            actual_output_path = temp_output_dir / f"{file_id}.BirdNET.results.csv"
            
            detections = self.parse_results(actual_output_path)
            
            duration = detections[-1].end_time if detections else 0.0
            
            analysis_time_ms = int((time.time() - start_time) * 1000)
            
            logger.info(f"Processing duration: {analysis_time_ms} ms, Number of detections: {len(detections)}")
            
            return BirdAnalysisResponse(
                filename=file.filename,
                duration_seconds=duration,
                analysis_time_ms=analysis_time_ms,
                detections=detections
            )
            
        finally:
            # Cleanup
            if temp_audio_path.exists():
                temp_audio_path.unlink()
            if temp_output_dir.exists():
                shutil.rmtree(temp_output_dir, ignore_errors=True)
            logger.info("Cleanup completed")
